sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  docker
  
script:
  - pip install pipenv
  # Run the unitary tests excluding the expensive computations
  - pipenv install --dev --skip-lock
  - cd mdstudio && python -m unittest discover
