sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  docker
install:
  - pip install codecov
  - pip install pipenv
  - pipenv install --dev --skip-lock
script:
  # Run the unitary tests excluding the expensive computations
  - cd mdstudio && python -m unittest discover -vvv
after_success:
  - codecov