sudo: required
language: python
python:
  - "2.7"

services:
  docker
  
script:
  # Run the unitary tests excluding the expensive computations
  - bash installer.sh

branches:
  only:
   - master
   - develop
