sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  docker
  
script:
  # Run the unitary tests excluding the expensive computations
  - pipenv install --dev

branches:
  only:
   - master
   - develop
