sudo: required
language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DOCKER_COMPOSE_VERSION=1.21.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

install:
  - pip install codecov
  - pip install pipenv
  - pipenv install --dev --skip-lock

script:
  # Run the unitary tests excluding the expensive computations
  - (cd mdstudio && coverage run -m unittest discover -vvv)
  - (cd core/logger && coverage run -m unittest discover -vvv)
  - (cd core/db && coverage run -m unittest discover -vvv)
  # Test docker compose
  - (docker-compose up -d crossbar && pip install -e components/lie_echo)
  - (cd tests && python -m lie_echo && python test_crossbar.py && python check_echo_output.py)

after_success:
  - codecov
