sudo: required
language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
    - python: "2.7"
  
env:
  - DOCKER_COMPOSE_VERSION=1.21.0 MD_CONFIG_ENVIRONMENTS=dev,docker
  
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

install:
  - pip install codecov
  - pip install pip-tools
  - pipenv install --dev --skip-lock

script:
  # Run the unitary tests excluding the expensive computations 
  - (cd mdstudio && coverage run --branch -m unittest discover -vvv)
  - (cd core/logger && coverage run --branch -m unittest discover -vvv)
  - (cd core/db && coverage run --branch -m unittest discover -vvv)
  - (cd core/schema && coverage run --branch -m unittest discover -vvv)
  # Test docker compose
  - (docker-compose up -d crossbar && pip install -e components/lie_echo)
  - pip install docker retrying
  - (cd tests && python check_docker_compose.py)
  - (cd tests && (python -m lie_echo &) && sleep 5 && (python test_crossbar.py &) && sleep 5 && python check_echo_output.py)
  # kill microservice
  - (ps axf | grep lie_echo | grep -v grep | awk '{print "kill -9 " $1}' | sh)

after_success:
  - coverage combine mdstudio/.coverage core/logger/.coverage core/db/.coverage core/schema/.coverage
  - codecov

