sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  docker
install:
  - pip install codecov
  - pip install pipenv
  - pipenv install --dev --skip-lock
script:
  # Run the unitary tests excluding the expensive computations
  - (cd mdstudio && coverage run --branch -m unittest discover -vvv)
  - (cd core/logger && coverage run --branch -m unittest discover -vvv)
  - (cd core/db && coverage run --branch -m unittest discover -vvv)
  - (cd core/schema && coverage run --branch -m unittest discover -vvv)
after_success:
  - coverage combine mdstudio/.coverage core/logger/.coverage core/db core/schema/.coverage
  - codecov