sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  docker
install:
  - pip install codecov
  - pip install pipenv
  - pipenv install --dev --skip-lock
script:
  # Run the unitary tests excluding the expensive computations
  - cd mdstudio && coverage run -m unittest discover -vvv
  - cd core/logger && coverage run -m unittest discover -vvv
  - cd core/db && coverage run -m unittest discover -vvv
after_success:
  - codecov