version: '2'
services:

    crossbar:
        # image: crossbario/crossbar
        build:
            context: ./docker/crossbar
        links:
            - mongo
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - crossbar_pipcache:/root/.cache
            - crossbar_pip:/usr/local/lib/python3.5/site-packages
            - crossbar_pipenv:/root/.local/share/virtualenvs
        environment:
            - _LIE_MONGO_HOST=mongo
            - _LIE_GLOBAL_LOG=1
        env_file: .env

    md:
        extends:
            file: docker-compose-common.yml
            service: base-py2
        volumes:
            # mount component
            - ./components/lie_md:/app/components/lie_md
            # mount config directory
            - ./data/lie_md:/app/data/lie_md
        environment:
            - COMPONENT=lie_md
        links:
            - crossbar
    
    atb:
        extends:
            file: docker-compose-common.yml
            service: base-py3
        volumes:
            # mount component
            - ./components/lie_atb:/app/components/lie_atb
            # mount config directory
            - ./data/lie_atb:/app/data/lie_atb
        environment:
            - COMPONENT=lie_atb
        links:
            - crossbar
    
    cli:
        extends:
            file: docker-compose-common.yml
            service: base-py3
        volumes:
            # mount component
            - ./components/lie_cli:/app/components/lie_cli
            # mount config directory
            - ./data/lie_cli:/app/data/lie_cli
            # mount cache volumes
            - cli_pipcache:/root/.cache
            - cli_pip:/usr/local/lib/python3.5/site-packages
        environment:
            - COMPONENT=lie_cli
        links:
            - crossbar

    mongo:
        image: mongo:latest
        command: mongod  --noauth
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db


volumes:
    mongo:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_pip:
        driver: "local"
    crossbar_pipenv:
        driver: "local"
    cli_pipcache:
        driver: "local"
    cli_pip:
        driver: "local"