version: '2'
services:


    applications:
        image: tianon/true
        volumes:
            - .:/app
            # cache directories for faster building times
            - /root/.cache/pip
            - /root/.npm


    workspace:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                - INSTALL_WORKSPACE_SSH=true
        volumes_from:
            - applications
        links:
            - mongo
        ports:
            - "65432:22"
            - "80:8080"
            - "5000:5000"
            - "3001:3001"
        tty: true

    mongo:
        image: mongo:latest
        command: mongod  --noauth
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db

volumes:
    mongo:
        driver: "local"