version: '3'
services:

    workspace:
        build:
            context: ./docker/workspace
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - workspace_pipcache:/root/.cache
            - workspace_venv:/root/mdstudio
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    crossbar:
        build:
            context: ./docker/crossbar
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
        command: mongod  --noauth --bind_ip_all


    redis:
        build:
            context: docker/redis-cluster
            args:
                redis_version: 4.0.8
        ports:
            - "7000:7000"
            - "7001:7001"
        volumes:
            - redis:/data/db

    # Resources available to all the microservices
    common_resources:
      image: mdstudio/common_resources:0.0.1
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
            
    # LIE components with local volume mounted
    mdstudio_haddock:
      image: mdstudio/mdstudio_haddock
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/mdstudio_haddock:/tmp/mdstudio/mdstudio_haddock

    lie_pylie:
      image: mdstudio/lie_pylie:0.0.4
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/lie_pylie:/tmp/mdstudio/lie_pylie

    mdstudio_propka:
      image: mdstudio/mdstudio_propka
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/mdstudio_propka:/tmp/mdstudio/mdstudio_propka

    mdstudio_atb:
      image: mdstudio/mdstudio_atb
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/mdstudio_atb:/tmp/mdstudio/mdstudio_atb

    mdstudio_amber:
      image: mdstudio/mdstudio_amber
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/mdstudio_amber:/tmp/mdstudio/mdstudio_amber

    mdstudio_structures:
      image: mdstudio/mdstudio_structures
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/mdstudio_structures:/tmp/mdstudio/mdstudio_structures

    mdstudio_smartcyp:
      image: mdstudio/mdstudio_smartcyp
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - ${WORKDIR}/mdstudio_smartcyp:/tmp/mdstudio/mdstudio_smartcyp

volumes:
    mongo:
        driver: "local"
    redis:
        driver: "local"
    workspace_pipcache:
        driver: "local"
    workspace_venv:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_venv:
        driver: "local"
    cli_pipcache:
        driver: "local"
    cli_pip:
        driver: "local"
