
version: '3'
services:

    workspace:
        build:
            context: ./docker/workspace
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - workspace_pipcache:/root/.cache
            - workspace_pipenv:/root/.local/share/virtualenvs
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    crossbar:
        build:
            context: ./docker/crossbar
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - crossbar_pipcache:/root/.cache
            - crossbar_pipenv:/root/.local/share/virtualenvs
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    # echo:
    #     extends:
    #         file: docker-compose-common.yml
    #         service: base-py3
    #     volumes:
    #         # mount component
    #         - ./components/lie_echo:/app/components/lie_echo
    #     environment:
    #         - COMPONENT=lie_echo
    #     links:
    #         - crossbar

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
        command: mongod  --noauth --bind_ip_all


    redis:
        build:
            context: docker/redis-cluster
            args:
                redis_version: 4.0.8
        ports:
            - "7000:7000"
            - "7001:7001"
        volumes:
            - redis:/data/db

    # LIE components
    lie_amber:
      image: lie_amber:test
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - "./data/crossbar/server_cert.pem:/app/data/crossbar/server_cert.pem"

    lie_structures:
      image: lie_structures:test
      links:
        - crossbar
      environment:
        - CROSSBAR_HOST=crossbar
      volumes:
        - "./data/crossbar/server_cert.pem:/app/data/crossbar/server_cert.pem"


volumes:
    mongo:
        driver: "local"
    redis:
        driver: "local"
    workspace_pipcache:
        driver: "local"
    workspace_pipenv:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_pipenv:
        driver: "local"
    cli_pipcache:
        driver: "local"
    cli_pip:
      driver: "local"
