version: '2'
services:


    applications:
        image: tianon/true
        volumes:
            - .:/app
            # cache directories for faster building times
            #- /app/app/node_modules
            - /root/.local/share/virtualenvs
            - /root/.cache/pip
            - /root/.npm


    workspace:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                - INSTALL_WORKSPACE_SSH=true
        volumes_from:
            - applications
        links:
            - mongo
        ports:
            # use non standard ssh port
            - "65432:22"
            # show on normal http port
            - "80:8080"
            # needed for support on development
            - "8080:8080"
            # gulp serve
            - "5000:5000"
            - "3001:3001"
            # sphinx autobuild
            - "8000:8000"
        tty: true

    mongo:
        image: mongo:latest
        command: mongod  --noauth
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db

volumes:
    mongo:
        driver: "local"