version: '2'
services:

    crossbar:
        # image: crossbario/crossbar
        build:
            context: ./docker/crossbar
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - crossbar_pipcache:/root/.cache
            - crossbar_pipenv:/root/.local/share/virtualenvs
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    md:
        extends:
            file: docker-compose-common.yml
            service: base-py2
        volumes:
            # mount component
            - ./components/lie_md:/app/components/lie_md
        environment:
            - COMPONENT=lie_md
        links:
            - crossbar
    
    atb:
        extends:
            file: docker-compose-common.yml
            service: base-py3
        volumes:
            # mount component
            - ./components/lie_atb:/app/components/lie_atb
        environment:
            - COMPONENT=lie_atb
        links:
            - crossbar
    
    cli:
        extends:
            file: docker-compose-common.yml
            service: base-py3
        volumes:
            # mount component
            - ./components/lie_cli:/app/components/lie_cli
        environment:
            - COMPONENT=lie_cli
        links:
            - crossbar

    mongo:
        image: mongo:latest
        command: mongod  --noauth
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db


    redis:
        image: grokzen/redis-cluster
        ports:
            - "7000:7000"
            - "7001:7001"
        volumes:
            - redis:/data/db


    redis-local:
        build:
            context: docker/docker-redis-cluster
            args:
                redis_version: '3.2.9'
        ports:
            - "7010:7010"
            - "7011:7011"
        volumes:
            - redis:/data/db

volumes:
    mongo:
        driver: "local"
    redis:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_pip:
        driver: "local"
    crossbar_pipenv:
        driver: "local"
    cli_pipcache:
        driver: "local"
    cli_pip:
        driver: "local"